# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Release Python Package

on: [push]

permissions:
  contents: write
  discussions: write

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build package
      id: build_package
      run: |
        python -m build
        echo "BUILD_VERSION=$(python setup.py --version)" >> "$GITHUB_OUTPUT"
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.2
      with:
        custom_tag:  ${{steps.build_package.outputs.BUILD_VERSION}}
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ steps.tag_version.outputs.new_tag }}
        name: Release ${{ steps.tag_version.outputs.new_tag }}
        body: ${{ steps.tag_version.outputs.changelog }}
        artifacts: "LICENSE,./dist/*.tar.gz,./dist/*.whl"
        token: ${{ secrets.GITHUB_TOKEN }}
